# Manuscript Data Wrangling for Archival

In [1]:
# Load packages 
import pandas as pd
import geopandas as gpd

In [2]:
pd.set_option('display.max_columns', None)

# Read in GeoJSON of all 
burdens = gpd.read_file('/home/kat/github/data-analysis/data/december-geoda-output-burdens.geojson')

indicators = gpd.read_file('/home/kat/github/data-analysis/data/december-geoda-output-burdens.geojson')

In [3]:
indicators.head()

,GEOID10,SF,CF,DF_PFS,AF_PFS,HDF_PFS,DSF_PFS,EBF_PFS,EALR_PFS,EBLR_PFS,EPLR_PFS,HBF_PFS,LLEF_PFS,LIF_PFS,LMI_PFS,PM25F_PFS,HSEF,P100_PFS,P200_I_PFS,AJDLI_ET,LPF_PFS,KP_PFS,NPL_PFS,RMP_PFS,TSDF_PFS,TPF,TF_PFS,UF_PFS,WF_PFS,UST_PFS,N_WTR,N_WKFC,N_CLT,N_ENY,N_TRN,N_HSG,N_PLN,N_HLTH,SN_C,SN_C_V10,SN_GRAND,SN_T,DLI,ALI,PLHSE,LMILHSE,ULHSE,EPL_ET,EAL_ET,EBL_ET,EB_ET,PM25_ET,DS_ET,TP_ET,LPP_ET,HRS_ET,KP_ET,HB_ET,RMP_ET,NPL_ET,TSDF_ET,WD_ET,UST_ET,DB_ET,A_ET,HD_ET,LLE_ET,UN_ET,LISO_ET,POV_ET,LMI_ET,IA_LMI_ET,IA_UN_ET,IA_POV_ET,TC,CC,IAULHSE,IAPLHSE,IALMILHSE,IALMIL_78,IAPLHS_79,IAULHS_80,LHE,IALHE,IAHSEF,N_CLT_EOMI,N_ENY_EOMI,N_TRN_EOMI,N_HSG_EOMI,N_PLN_EOMI,N_WTR_EOMI,N_HLTH_90,N_WKFC_91,FPL200S,FPL200P,N_WKFC_94,TD_ET,TD_PFS,FLD_PFS,WFR_PFS,FLD_ET,WFR_ET,ADJ_ET,IS_PFS,IS_ET,AML_ET,FUDS_RAW,FUDS_ET,IMP_FLG,DM_B,DM_AI,DM_A,DM_HI,DM_T,DM_W,DM_H,DM_O,AGE_10,AGE_MIDDLE,AGE_OLD,TA_COU_119,TA_PERC,TA_PERC_FE,UI_EXP,THRHLD,G_STR,C_ID,PP_VAL,geometry
0,01073001100,Alabama,Jefferson County,0.96,0.85,0.72,0.84,0.86,0.21,0.78,0.61,0.64,0.97,0.12,0.82,0.82,0.08,0.62,0.65,1,0.39,0.21,0.75,0.90,0.48,4781.0,0.39,0.02,0.96,0.52,1,0,0,0,0,1,1,1,1,0,0,None,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,5,4.0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,1,1,1,1,0,1,0.0,0,0,0.45,0.49,0.84,0,0,0,0.26,0,0,None,0,0,0.96,0.01,0.0,0.0,0.00,0.01,0.00,0.00,0.13,0.66,0.20,0.0,0.0,0.0,Nation,21,0.000050,1,0.0002,"MULTIPOLYGON (((-86.88244 33.55233, -86.88187 ..."
1,01073001400,Alabama,Jefferson County,0.98,0.83,0.92,0.93,0.97,0.08,0.91,0.55,0.34,0.96,0.58,0.83,0.83,0.17,0.86,0.78,1,0.84,0.50,0.86,0.87,0.80,1946.0,0.95,0.90,0.84,0.64,0,1,1,1,1,1,0,1,1,1,0,None,1,0,0,0,1,0,0,1,1,0,1,1,0,1,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,0,9,6.0,0,0,0,0.0,0.0,0.0,1,0,0.0,1,1,1,1,0,0,1,1,1,0.0,1,0,0.37,0.88,0.33,0,0,1,0.55,0,0,None,0,0,0.91,0.00,0.0,0.0,0.00,0.00,0.06,0.07,0.08,0.72,0.18,0.0,0.0,0.0,Nation,21,0.000070,1,0.0001,"MULTIPOLYGON (((-86.84088 33.52759, -86.83782 ..."
2,01073002000,Alabama,Jefferson County,0.98,0.97,0.94,0.76,0.93,0.08,0.64,0.63,0.89,0.95,0.54,0.93,0.81,0.23,0.98,0.96,1,0.82,0.59,0.75,0.37,0.73,4080.0,0.61,0.94,0.83,0.81,0,1,0,1,0,0,0,1,1,1,0,None,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,1,1,0,0,0,8,3.0,0,0,0,0.0,0.0,0.0,1,0,0.0,0,1,0,0,0,0,1,1,1,0.0,1,0,0.52,0.84,0.33,0,0,1,0.23,0,0,None,0,0,0.63,0.00,0.0,0.0,0.00,0.27,0.07,0.02,0.15,0.71,0.12,0.0,0.0,0.0,Nation,21,0.000051,1,0.0003,"MULTIPOLYGON (((-86.7139 33.5393, -86.71435 33..."
3,01073003802,Alabama,Jefferson County,0.95,0.91,0.62,0.79,0.97,0.07,0.90,0.55,0.87,0.86,0.12,0.79,0.83,0.14,0.73,0.85,1,0.83,0.94,0.60,0.74,0.68,5291.0,0.49,0.87,0.16,0.85,0,0,1,1,0,1,0,1,1,1,0,None,1,1,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,6,4.0,0,0,0,0.0,0.0,0.0,1,0,0.0,1,1,0,1,0,0,1,0,1,0.0,1,0,0.75,0.82,0.33,0,0,1,0.49,0,0,None,0,0,0.97,0.00,0.0,0.0,0.00,0.01,0.00,0.00,0.14,0.72,0.13,0.0,0.0,0.0,Nation,21,0.000050,1,0.0002,"MULTIPOLYGON (((-86.90317 33.47177, -86.90284 ..."
4,01073004000,Alabama,Jefferson County,0.99,0.96,0.96,0.86,0.98,0.00,0.95,0.55,0.92,0.99,0.71,0.98,0.84,0.17,0.95,0.96,1,0.67,0.67,0.71,0.86,0.73,2533.0,0.49,0.98,0.19,0.66,0,1,1,1,0,1,0,1,1,1,0,None,1,1,1,1,1,0,0,1,1,0,0,0,0,1,0,1,0,0,0,0,0,1,1,1,1,1,0,1,1,0,0,0,11,5.0,0,0,0,0.0,0.0,0.0,1,0,0.0,1,1,0,1,0,0,1,1,1,0.0,1,0,0.33,0.80,0.33,0,0,1,0.68,0,0,None,0,0,0.85,0.00,0.0,0.0,0.04,0.06,0.06,0.00,0.06,0.68,0.24,0.0,0.0,0.0,Nation,21,0.000062,1,0.0001,"MULTIPOLYGON (((-86.85463 33.48754, -86.85554 ..."

In [4]:
# Wrangling burdens geoda data
burdens_cleaned = burdens[['GEOID10', 'SF', 'CF', 'CC', 'TC', 'G_STR', 'C_ID', 'PP_VAL', 'geometry']].rename(columns={
    'SF': 'State',
    'CF': 'County',
    'CC': 'Total_Burdens',
    'TC': 'Total_Indicators',
    'C_ID': 'C_ID_Burdens',
    'G_STR': 'Gi_Z_Burdens',
    'PP_VAL': 'Gi_P_Burdens'
})
burdens_cleaned.head()

,GEOID10,State,County,Total_Burdens,Total_Indicators,Gi_Z_Burdens,C_ID_Burdens,Gi_P_Burdens,geometry
0,01073001100,Alabama,Jefferson County,4.0,5,0.000050,1,0.0002,"MULTIPOLYGON (((-86.88244 33.55233, -86.88187 ..."
1,01073001400,Alabama,Jefferson County,6.0,9,0.000070,1,0.0001,"MULTIPOLYGON (((-86.84088 33.52759, -86.83782 ..."
2,01073002000,Alabama,Jefferson County,3.0,8,0.000051,1,0.0003,"MULTIPOLYGON (((-86.7139 33.5393, -86.71435 33..."
3,01073003802,Alabama,Jefferson County,4.0,6,0.000050,1,0.0002,"MULTIPOLYGON (((-86.90317 33.47177, -86.90284 ..."
4,01073004000,Alabama,Jefferson County,5.0,11,0.000062,1,0.0001,"MULTIPOLYGON (((-86.85463 33.48754, -86.85554 ..."

In [5]:
# Wrangling burdens geoda data
indicators_cleaned = indicators[['GEOID10', 'SF', 'CF', 'CC', 'TC', 'G_STR', 'C_ID', 'PP_VAL', 'geometry']].rename(columns={
    'SF': 'State',
    'CF': 'County',
    'CC': 'Total_Burdens',
    'TC': 'Total_Indicators',
    'C_ID': 'C_ID_Indicators',
    'G_STR': 'Gi_Z_Indicators',
    'PP_VAL': 'Gi_P_Indicators'
})
indicators_cleaned.head()

,GEOID10,State,County,Total_Burdens,Total_Indicators,Gi_Z_Indicators,C_ID_Indicators,Gi_P_Indicators,geometry
0,01073001100,Alabama,Jefferson County,4.0,5,0.000050,1,0.0002,"MULTIPOLYGON (((-86.88244 33.55233, -86.88187 ..."
1,01073001400,Alabama,Jefferson County,6.0,9,0.000070,1,0.0001,"MULTIPOLYGON (((-86.84088 33.52759, -86.83782 ..."
2,01073002000,Alabama,Jefferson County,3.0,8,0.000051,1,0.0003,"MULTIPOLYGON (((-86.7139 33.5393, -86.71435 33..."
3,01073003802,Alabama,Jefferson County,4.0,6,0.000050,1,0.0002,"MULTIPOLYGON (((-86.90317 33.47177, -86.90284 ..."
4,01073004000,Alabama,Jefferson County,5.0,11,0.000062,1,0.0001,"MULTIPOLYGON (((-86.85463 33.48754, -86.85554 ..."

In [6]:
# Check if the three columns match between dataframes
match_check = burdens_cleaned[['GEOID10', 'Total_Burdens', 'Total_Indicators']].equals(
    indicators_cleaned[['GEOID10', 'Total_Burdens', 'Total_Indicators']]
)

print(match_check)

True

In [7]:
# Join data on overlapping columns
overlap = set(burdens_cleaned.columns) & set(indicators_cleaned.columns)

joined = burdens_cleaned.merge(
    indicators_cleaned,
    on=list(overlap),
    how='inner'
)

joined.head()

,GEOID10,State,County,Total_Burdens,Total_Indicators,Gi_Z_Burdens,C_ID_Burdens,Gi_P_Burdens,geometry,Gi_Z_Indicators,C_ID_Indicators,Gi_P_Indicators
0,01073001100,Alabama,Jefferson County,4.0,5,0.000050,1,0.0002,"MULTIPOLYGON (((-86.88244 33.55233, -86.88187 ...",0.000050,1,0.0002
1,01073001400,Alabama,Jefferson County,6.0,9,0.000070,1,0.0001,"MULTIPOLYGON (((-86.84088 33.52759, -86.83782 ...",0.000070,1,0.0001
2,01073002000,Alabama,Jefferson County,3.0,8,0.000051,1,0.0003,"MULTIPOLYGON (((-86.7139 33.5393, -86.71435 33...",0.000051,1,0.0003
3,01073003802,Alabama,Jefferson County,4.0,6,0.000050,1,0.0002,"MULTIPOLYGON (((-86.90317 33.47177, -86.90284 ...",0.000050,1,0.0002
4,01073004000,Alabama,Jefferson County,5.0,11,0.000062,1,0.0001,"MULTIPOLYGON (((-86.85463 33.48754, -86.85554 ...",0.000062,1,0.0001

In [8]:
# Burdens
joined['VCS_burdens'] = ((joined['C_ID_Burdens'] == 2) & (joined['Gi_P_Burdens'] < 0.01)).astype(int)
joined['CS_burdens'] = ((joined['C_ID_Burdens'] == 2) & (joined['Gi_P_Burdens'] >= 0.01) & (joined['Gi_P_Burdens'] < 0.05)).astype(int)
joined['HS_burdens'] = ((joined['C_ID_Burdens'] == 1) & (joined['Gi_P_Burdens'] >= 0.01) & (joined['Gi_P_Burdens'] < 0.05)).astype(int)
joined['VHS_burdens'] = ((joined['C_ID_Burdens'] == 1) & (joined['Gi_P_Burdens'] < 0.01)).astype(int)

# Indicators
joined['VCS_indicators'] = ((joined['C_ID_Indicators'] == 2) & (joined['Gi_P_Indicators'] < 0.01)).astype(int)
joined['CS_indicators'] = ((joined['C_ID_Indicators'] == 2) & (joined['Gi_P_Indicators'] >= 0.01) & (joined['Gi_P_Indicators'] < 0.05)).astype(int)
joined['HS_indicators'] = ((joined['C_ID_Indicators'] == 1) & (joined['Gi_P_Indicators'] >= 0.01) & (joined['Gi_P_Indicators'] < 0.05)).astype(int)
joined['VHS_indicators'] = ((joined['C_ID_Indicators'] == 1) & (joined['Gi_P_Indicators'] < 0.01)).astype(int)

# Drop C_ID columns
# joined = joined.drop(columns=['C_ID_Burdens', 'C_ID_Indicators'])

joined = joined[[c for c in joined.columns if c != 'geometry'] + ['geometry']]

In [9]:
joined.head()

,GEOID10,State,County,Total_Burdens,Total_Indicators,Gi_Z_Burdens,C_ID_Burdens,Gi_P_Burdens,Gi_Z_Indicators,C_ID_Indicators,Gi_P_Indicators,VCS_burdens,CS_burdens,HS_burdens,VHS_burdens,VCS_indicators,CS_indicators,HS_indicators,VHS_indicators,geometry
0,01073001100,Alabama,Jefferson County,4.0,5,0.000050,1,0.0002,0.000050,1,0.0002,0,0,0,1,0,0,0,1,"MULTIPOLYGON (((-86.88244 33.55233, -86.88187 ..."
1,01073001400,Alabama,Jefferson County,6.0,9,0.000070,1,0.0001,0.000070,1,0.0001,0,0,0,1,0,0,0,1,"MULTIPOLYGON (((-86.84088 33.52759, -86.83782 ..."
2,01073002000,Alabama,Jefferson County,3.0,8,0.000051,1,0.0003,0.000051,1,0.0003,0,0,0,1,0,0,0,1,"MULTIPOLYGON (((-86.7139 33.5393, -86.71435 33..."
3,01073003802,Alabama,Jefferson County,4.0,6,0.000050,1,0.0002,0.000050,1,0.0002,0,0,0,1,0,0,0,1,"MULTIPOLYGON (((-86.90317 33.47177, -86.90284 ..."
4,01073004000,Alabama,Jefferson County,5.0,11,0.000062,1,0.0001,0.000062,1,0.0001,0,0,0,1,0,0,0,1,"MULTIPOLYGON (((-86.85463 33.48754, -86.85554 ..."

In [ ]:
# joined.to_file('../data/final_output.geojson', driver='GeoJSON')